version: "2"

linters:
  default: none
  enable:
    - logchecklint

linters-settings:
  custom:
    logchecklint:
      type: module
      description: "Linter for checking log messages"
      original-url: github.com/manakowpavel/logchecklint